project_id = "tjduhugyqcaiygexpptp"

[db.seed]
enabled = true
sql_paths = ['./seed.sql']

[functions.ai-chat]
verify_jwt = false

[functions.translate-definition]
verify_jwt = false

[functions.review-writing]
verify_jwt = false

[functions.generate-practice]
verify_jwt = false
